IF(
  AND(
    ISBLANK(Opportunity.UTM_Medium__c),
    NOT(ISBLANK(Opportunity.FundraiseUpId__c))
  ),
  "unattributed",
  IF(
    ISBLANK(Opportunity.UTM_Medium__c),
    "",
    Opportunity.UTM_Medium__c
  )
)